install:
	pip install --upgrade pip &&\
		pip install -r src\requirements.txt

test:
	python -m pytest -vv src\test_hello.py

format:
	black *.py

lint:
	pylint --disable=R,C src\hello.py

all: install lint test