# This workflow will install Python dependencies, run tests, lint and format code with a single version of Python

name: Python application test with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        make -f MakeFile install
    - name: Lint with pylint
      run: |
        make -f MakeFile lint
    - name: Test with pytest
      run: |
        make -f MakeFile test
    - name: Format code with black
      run: |
        make -f MakeFile format
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: user/app:latest
