# This workflow will install Python dependencies, run tests, lint and format code with a single version of Python

name: Python application test with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        make -f MakeFile install
    - name: Lint with pylint
      run: |
        make -f MakeFile lint
    - name: Test with pytest
      run: |
        make -f MakeFile test
    - name: Format code with black
      run: |
        make -f MakeFile format
        
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: bigocean98/test_repo
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
